default:
  tags: [latest]
   


stages:
  - build
  - style
  - test
  - deploy

build-job:
  stage: build
  script:
    - cd src/cat
    - make
  artifacts:
    path: 
      - compiled-code/
    expire_in: 1 week


# test-style:
#   stage: style
#   script:
#     - cd src/cat
#     - make check

# test-job2:
#   stage: test
#   script:
#     - cd src/cat
#     - make test
#   dependencies:
#     - build
#   artifacts:
#     path:
#       - test-result/
#     expire_in: 30 days

# deploy-prod:
#   stage: deploy
#   script:
#     - cd src/cat
#     - make deploy
#   dependencies:
#     - test
