default:
  tags: [latest]
   


stages:
  - build
  - style
  - test
  - deploy

build-job:
  stage: build
  script:
    - cd src/cat
    - make
  artifacts:
    paths: 
      - src/cat/s21_cat
    expire_in: 30 days


test-style:
  stage: style
  script:
    - cd src/cat
    - make check

# test-job2:
#   stage: test
#   script:
#     - cd src/cat
#     - make test
#   dependencies:
#     - build-job
#   artifacts:
#     paths:
#       - src/cat/test-result/
#     expire_in: 30 days

# deploy-prod:
#   stage: deploy
#   script:
#     - cd src/cat
#     - make deploy
#   dependencies:
#     - test-job2
