default:
  tags: [latest]
   


stages:
  - build
  - style
  - test

build-job:
  stage: build
  script:
    - cd src/cat
    - make

test-style:
  stage: style
  script:
    - cd src/cat
    - make chack

test-job2:
  stage: test
  script:
    - cd src/cat
    - make test

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys anything from the $CI_COMMIT_BRANCH branch."
