default:
  tags: [latest]
   
stages:
  - build
  - style
  - test
  - deploy

build-job:
  stage: build
  script:
    - cd src/cat
    - make
    - cd ../grep
    - make
  artifacts:
    paths: 
      - src/cat/compiled-code/s21_cat
      - src/grep/compiled-code/s21_grep
    expire_in: 30 days
  after_script:
    - cd src
    - ls -la
    - bash telegram_bot.sh Build


test-style:
  stage: style
  script:
    - cd src/cat
    - make check
    - cd ../grep
    - make check
  after_script:
    - cd src
    - ls -la
    - bash telegram_bot.sh Style

test-functional:
  stage: test
  script:
    - cd src/cat
    - make test
    - cd ../grep
    - make test
  dependencies:
    - build-job
  artifacts:
    paths:
      - src/cat/test-results
      - src/grep/test-results
    expire_in: 30 days
  after_script:
    - cd src
    - ls -la
    - bash telegram_bot.sh TestFunction

deploy-prod:
  stage: deploy
  when: manual
  script:
    - cd src
    - bash transfer.sh
  dependencies:
    - build-job
  after_script:
    - cd src
    - ls -la
    - bash telegram_bot.sh Deploy
    
