default:
  tags: [latest]
   


stages:
  - build
  - style
  - test
  - deploy

build-job:
  stage: build
  script:
    - cd src/cat
    - make

test-style:
  stage: style
  script:
    - cd src/cat
    - make check

test-job2:
  stage: test
  script:
    - cd src/cat
    - make test

# deploy-prod:
#   stage: deploy
#   script:
#     - cd src/cat
#     - make deploy
